feat (MELB): "Songbird" additions
WitchFreya/SWSAddons pull request #150
Opened 2024-02-27 18:42 UTC by EidolonForgery

Add: Shrike light CAS helicopter
Add: Magpie light transport helicopter
Add: Talon missiles + launcher
Add: Rake missiles + launcher
- Hides MELB variants that are now outdated

2024-02-27 18:43 UTC, EidolonForgery reviewed
I want this off my desk so bad. MFD is soul-draining. At least I got the grease pencil to fuck off

2024-02-27 20:31 UTC, WitchFreya commented on addons/patches/melb/CfgAmmo.inc
> +		cmimmunity = 1;
```suggestion
    ITEM_META(0);
		cmImmunity = 1;
```

2024-02-27 20:33 UTC, WitchFreya commented on addons/patches/melb/CfgAmmo.inc
> +	{
Double check this + the others, I've run into issues omitting file extensions in some places before so for safety I just include them whether or not they're necessary.
```suggestion
		model = "melb\proxies\m229_fly.p3d";
```

2024-02-27 20:33 UTC, WitchFreya commented on addons/patches/melb/CfgAmmo.inc
> +		model = "melb\proxies\m229_fly";
```suggestion
		proxyShape = "melb\proxies\m229_proxy.p3d";
```

2024-02-27 20:33 UTC, WitchFreya commented on addons/patches/melb/CfgAmmo.inc
> +	class SWS_M_Rake : SWS_Dumbfire_Base {
```suggestion
		model = "melb\proxies\m261_mpsm_fly.p3d";
```

2024-02-27 20:33 UTC, WitchFreya commented on addons/patches/melb/CfgAmmo.inc
> +	class SWS_M_Rake : SWS_Dumbfire_Base {
```suggestion
		proxyShape = "melb\proxies\m261_mpsm_proxy.p3d";
```

2024-02-27 20:34 UTC, WitchFreya commented on addons/patches/melb/CfgAmmo.inc
> +class cfgAmmo {
```suggestion
class CfgAmmo {
```

2024-02-27 20:34 UTC, WitchFreya commented on addons/patches/melb/CfgMagazines.inc
> +class cfgMagazines
```suggestion
class CfgMagazines
```

2024-02-27 20:42 UTC, WitchFreya requested changes
Mostly looks good; I'd prefer it lives in two places though. The stuff that modifies MELB's base behavior should be in `addons\patches\melb` with 
```cpp
#define SUBCOMPONENT melb
#define SUBCOMPONENT_BEAUTIFIED Mission Enhanced Little Bird
```

while the stuff that adds the Songbird should be a subcomponent in `addons\air\heli_songbird` with 
```cpp
#define SUBCOMPONENT heli_sonbird
#define SUBCOMPONENT_BEAUTIFIED Songbird
```

2024-02-27 20:47 UTC, EidolonForgery commented
> Mostly looks good; I'd prefer it lives in two places though. The stuff that modifies MELB's base behavior should be in `addons\patches\melb` with
> 
> ```c++
> #define SUBCOMPONENT melb
> #define SUBCOMPONENT_BEAUTIFIED Mission Enhanced Little Bird
> ```
> 
> while the stuff that adds the Songbird should be a subcomponent in `addons\air\heli_songbird` with
> 
> ```c++
> #define SUBCOMPONENT heli_sonbird
> #define SUBCOMPONENT_BEAUTIFIED Songbird
> ```

ouoeugouefoeughef

But, it will be done

2024-02-27 23:24 UTC, EidolonForgery commented
Hold please, addressing one or two small fixes that I should have already checked.

2024-02-29 16:47 UTC, WitchFreya approved these changes

2024-02-29 16:48 UTC, merged