feat (weapons): Add xMA-37k and remove flashlight
WitchFreya/SWSAddons pull request #175
Opened 2024-04-04 22:07 UTC by EidolonForgery

- add xMA-37k to SWS weapons
- remove its flashlight to prevent conflicts with attachments
- add it to the arsenal extension

Should resolve #174 .

2024-04-04 22:58 UTC, WitchFreya requested changes
The only major thing I can really see is that I'd prefer it to be named the SMA37K or MA37K-S instead to keep with other naming conventions.

2024-04-04 22:58 UTC, WitchFreya commented on addons/weapons/xma37k/script_component.hpp
> +#define SUBCOMPONENT_BEAUTIFIED SWS - XMA37K Carbine Prototype
Remove the SWS - from this.

2024-04-06 01:05 UTC, EidolonForgery reviewed
> The only major thing I can really see is that I'd prefer it to be named the SMA37K or MA37K-S instead to keep with other naming conventions. 

So, the Sx in our guns appears to be standing in for the standard X- designator used for eXperimental weapons. This is used as a prefix in all cases - XM8, XM22. The K here is for Kurz, after the MP5K, no doubt. 

With military firearms, the "M" stands for Model (Or Mk. for Mark, if the weapon originated in the Navy.)
So we can use either XMA-37K or sX-37K here. How strongly do you feel about this, is the question? I'd be fine with the SX-37K, but the SxMA-37K is just... too long.

2024-04-06 04:21 UTC, WitchFreya approved these changes

2024-04-06 04:22 UTC, merged