[Feat] tweaks to Viper weapon and sensor configuration, add CLA faction variant with unique texture
WitchFreya/SWSAddons pull request #7
Opened 2023-11-09 02:47 UTC by EmilyWinjum

Does basically what it says on the tin. For more complete details:
- Adds Metis-platform-based ATGM characteristics to the main cannon's arsenal
- Adds auto-lock features for gunner's turret on targets with an existing datalink illumination
- Adds lead indicator for datalink targets on the commander's gun
- Adds CLA (Captured) Viper variant with a special emblem to replace the UNSC livery
- Adds sticker decal variant for Fun Times :3

2023-11-10 18:02 UTC, WitchFreya requested changes

2023-11-10 18:02 UTC, WitchFreya commented on addons/vehicles/CfgAmmo.hpp
> +class Components;
Since these three are duplicated in both CfgVehicles and CfgAmmo, move them from both to the config.cpp file instead.

2023-11-10 19:06 UTC, EmilyWinjum commented on addons/vehicles/CfgMagazineWells.hpp
> +	class 120mm_Viper_AP
:) I wish. Apparently BI had better things to do than to not just hardcode munition types by cannon variant. I couldn't find any but would be *happily* proven wrong.

2023-11-10 19:07 UTC, EmilyWinjum commented on addons/vehicles/CfgWeapons/ViperCannon.inc
> +    displayName = "120/Viper";
Wound up giving it a proper XM designation for lore flavor

2023-11-11 18:55 UTC, WitchFreya approved these changes

2023-11-11 18:56 UTC, WitchFreya commented on addons/vehicles/CfgMagazineWells.hpp
> +	class 120mm_Viper_AP
Gotcha. Annoying. lgtm

2023-11-11 18:57 UTC, merged